### ISSUE TITLE
bin/sst-light-0.4/sst

### ISSUE THREAD

**Issue by lijiayi980130** [lasigeBioTM/BiOnt#8]
![image](https://user-images.githubusercontent.com/31726855/136157447-a66e5f8d-61cc-4fa6-a516-b424e0cf7a00.png)
hello,I want to know the location of these files above picture, the directory of "bin" is nothing,can you tell me where them is?

**Comment by lijiayi980130** [comment]
and the directory of "temp" is nothing,so some file is not open

**Comment by dpavot** [comment]
Hey!

After using the Dockerfile to set up the system or setting up directly with the BiOnt docker image available in the README file, you should follow reply #2 on the solved issues on the sst-light-0.4. Everything should be up and running.  

For used datasets, check  #3. The links for downloading pre-trained weights are available in the README file.
