### ISSUE TITLE
Assumed bug in preprocess_ids

### ISSUE THREAD

**Issue by etsnok** [lasigeBioTM/BiOnt#9]
In `ontologies_embeddings.py` in the method `preprocess_ids`, I assume that it's intended to collect the list of all ontology parents/ancestors. But wat it does instead is to take only the last ancestor. I guess correct would be something like: 
```
 idxs.append(id_to_index[d.replace('_', ':')])
```

**Comment by dpavot** [comment]
@etsnok yes! Great find. I updated the file!
